// <auto-generated />
namespace Talento.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrationwithoriginalmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrationwithoriginalmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041716519_Migration with original model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
